sudo: false
dist: xenial
language: csharp
cache: ccache
dotnet: 5.0.100
mono: none
solution: Ryujinx.sln
git:
  clone: true
  submodules: false
  depth: 3
addons: 
  apt: 
    sources:
    packages: 
      - p7zip-full
      - cmake
      - ninja-build
      - zenity
      - fuse
      - ccache
      - libsdl2-dev
      - libalut-dev
      - libglib2.0-0
      - libopenal-dev
install: 
  - mkdir -p "$HOME/.ccache"
  - cd ..
  - mv ./Ryujinx/ ./Ryujinx2
  - git clone --recursive https://github.com/Ryujinx/Ryujinx.git && cd Ryujinx
  - sed -i -e 's|DirectoryInfo logDir = new DirectoryInfo(Path.Combine(path, "Logs"));|DirectoryInfo logDir = new DirectoryInfo(Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.ApplicationData), "Ryujinx/Logs"));|g' Ryujinx.Common/Logging/Targets/FileLogTarget.cs
  - sed -i -e 's|string logPath = System.IO.Path.Combine(AppDomain.CurrentDomain.BaseDirectory, "Logs");|string logPath = System.IO.Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.ApplicationData), "Ryujinx/Logs");|g' Ryujinx/Ui/MainWindow.cs
  - dotnet restore
  - dotnet publish -c Release -r linux-x64 -v n
script: 
  - ls -al ${pwd}
  - chmod +x $TRAVIS_BUILD_DIR/../Ryujinx2/.travis/appimage.sh
  - $TRAVIS_BUILD_DIR/../Ryujinx2/.travis/appimage.sh
  - mkdir artifacts/
  - cp $TRAVIS_BUILD_DIR/Ryujinx-x86_64.AppImage* artifacts/
after_success: 
  - ls -al artifacts/
  - cd artifacts/
  - wget -c https://github.com/probonopd/uploadtool/raw/master/upload.sh
  - chmod a+x upload.sh
  - bash upload.sh Ryujinx-x86_64.AppImage*
branches: 
  except: 
    - /^(?i:continuous.*)$/
deploy: 
  api_key: $GITHUB_TOKEN
  file: artifacts/*
  file_glob: true
  provider: releases
  skip_cleanup: true
  true: 
    tags: true
