#!/bin/bash

mesa_glthread=true 
glsl_zero_init=true 
MESA_EXTENSION_OVERRIDE="-GL_KHR_texture_compression_astc_ldr -GL_KHR_texture_compression_astc_sliced_3d" 

mkdir -p $HOME/.local/share/icons/hicolor/scalable/apps && cp $APPDIR/Ryujinx.png $HOME/.local/share/icons/hicolor/scalable/apps

GITVER=`wget -qO- https://www.github.com/qurious-pixel/Ryujinx/releases/tag/continuous | grep qurious-pixel/Ryujinx/commit/ | cut -d '"' -f 2 | cut -d '/' -f 5 | awk '!x[$0]++'` 
APPVER=`cat $APPDIR/version.txt`

if [[ -z "$GITVER" ]]; then
	$APPDIR/AppRun-patched 
elif [ "$GITVER" = "$APPVER" ]; then
	$APPDIR/AppRun-patched 
else
	$APPDIR/update.sh
fi
