#!/bin/bash

mesa_glthread=true 
glsl_zero_init=true 
MESA_EXTENSION_OVERRIDE="-GL_KHR_texture_compression_astc_ldr -GL_KHR_texture_compression_astc_sliced_3d" 

mkdir -p $HOME/.local/share/icons/hicolor/scalable/apps && cp $APPDIR/Ryujinx.svg $HOME/.local/share/icons/hicolor/scalable/apps

GITVER=`wget -qO- https://www.github.com/qurious-pixel/Ryujinx/releases/tag/continuous | grep -o -P 'runs/.{0,9}' | cut -d '/' -f 2 | awk '!x[$0]++'` 
APPVER=`cat $APPDIR/version.txt`

if [[ -z "$GITVER" ]]; then
	$APPDIR/AppRun-patched
elif [ "$GITVER" = "$APPVER" ]; then
	$APPDIR/AppRun-patched
else
	$APPDIR/update.sh
fi
